"""User model with password added

Revision ID: d8c5d4c1dead
Revises: 8ec9362d8c5b
Create Date: 2023-06-02 14:48:08.267086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c5d4c1dead'
down_revision = '8ec9362d8c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_password_token')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
